### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by jroedel** [igneus/church-calendar-api#10]
This app is awesome, thanks so much for your work.  I'm an American living in Chile and I would love to get some API output in Spanish and/or German. Is there anything I can do to help localize?

Pax

**Comment by igneus** [comment]
Hi, support for Spanish has been ready for quite some time (see #7 ), but it hangs on me to release a new version of the `calendarium-romanum` gem, update this app, merge the PR and deploy it. I plan to get to it once the semester is over - end of June / beginning of July.

If you need the API with Spanish _now_ (and have the required Ruby skills), you could fork both calendarium-romanum and this app, merge the Spanish support in your fork and deploy it to your own hosting, e.g. et Heroku.
