### ISSUE TITLE
season_week is Incorrect

### ISSUE THREAD

**Issue by mkasberg** [igneus/church-calendar-api#3]
This endpoint reports a `season_week` of `15`: http://calapi.inadiutorium.cz/api/v0/en/calendars/default/2017/07/10

But it is actually the 14th week: http://usccb.org/bible/readings/071017.cfm

**Comment by mkasberg** [comment]
In particular, ordinary time leaves off on the last day before lent during the 8th week of ordinary time: http://calapi.inadiutorium.cz/api/v0/en/calendars/default/2017/02/28

```
{
  "date":"2017-02-28",
  "season":"ordinary",
  "season_week":8,
  "celebrations":[
    {
      "title":"",
      "colour":"green",
      "rank":"ferial",
      "rank_num":3.13
    }
  ],
  "weekday":"tuesday"
}
```

And picks up on the first day after easter in the 10th week of ordinary time, skipping the 9th week of ordinary time: http://calapi.inadiutorium.cz/api/v0/en/calendars/default/2017/06/05

```
{
  "date":"2017-06-05",
  "season":"ordinary",
  "season_week":10,
  "celebrations":[
    {
      "title":"Saint Boniface, bishop and martyr",
      "colour":"red",
      "rank":"memorial",
      "rank_num":3.1
    }
  ],
  "weekday":"monday"
}
```

**Comment by igneus** [comment]
@mkasberg Thank you very much for reporting this issue.

A fix is ready. I will deploy it in the near future, together with a few more updates. Then I will close this.

**Comment by mkasberg** [comment]
Awesome! Thanks for your work on this API.

**Comment by lbirir** [comment]
Hi @igneus thank you for your amazing work on the liturgical calendar API. 
When do you plan to deploy the fix?

**Comment by igneus** [comment]
@lbirir This week.

**Comment by igneus** [comment]
The fix is finally released and deployed to http://calapi.inadiutorium.cz. Thank you all for your patience.

**Comment by lbirir** [comment]
Thank you very much.
